services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # Ми підключаємо файл .env, щоб змінні були доступні всередині Python
    env_file:
      - .env
    # Але оскільки імена змінних у .env (DB_NAME) відрізняються від того,
    # що чекає settings.py (POSTGRES_DB), ми перепризначимо їх тут:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data: