# Generated by Django 6.0 on 2026-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса доставки'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота'),
        ),
    ]
