# Generated by Django 6.0 on 2026-01-07 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name='Код (slug)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AlterModelOptions(
            name='distributionitem',
            options={'verbose_name': 'Елемент розподілу', 'verbose_name_plural': 'Елементи розподілу'},
        ),
        migrations.AlterModelOptions(
            name='distributionplan',
            options={'verbose_name': 'План розподілу', 'verbose_name_plural': 'Плани розподілу'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Ресурс', 'verbose_name_plural': 'Ресурси'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Запас', 'verbose_name_plural': 'Запаси'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склади'},
        ),
        migrations.RemoveField(
            model_name='distributionitem',
            name='resource',
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.distributionplan', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse', verbose_name='Зі складу'),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='Виконано'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='Од. виміру'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.resource', verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Пріоритет (1-10)'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='quantity_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Виділено'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='quantity_requested',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Необхідна кількість'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resource', verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('partial', 'Частково виконана'), ('done', 'Виконана')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва складу'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='app.category', verbose_name='Категорія'),
        ),
    ]
