# Generated by Django 6.0 on 2026-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userrequest_delivery_address_userrequest_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='warehouse_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса відділення'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='warehouse_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID відділення НП'),
        ),
    ]
