# Generated by Django 6.0 on 2026-01-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_distributionitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionitem',
            options={'verbose_name': 'Трансфер', 'verbose_name_plural': 'Трансфери'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='category',
            name='criticality',
            field=models.FloatField(default=0.5, verbose_name='Критичність ресурсу'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='purpose',
            field=models.CharField(choices=[('military', 'Військові потреби / Фронт'), ('hospital', 'Медичні заклади / Реанімація'), ('disaster', 'Постраждалі від лих (Пожежі/Повені)'), ('refugees', 'ВПО / Біженці'), ('school', 'Освітні заклади / Діти'), ('personal', 'Особисті потреби')], default='personal', max_length=20, verbose_name='Призначення'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Технічний код'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.distributionplan'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userrequest'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='app.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва ресурсу'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Одиниця виміру'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.resource'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.warehouse'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='priority',
            field=models.FloatField(default=1.0, verbose_name='Розрахунковий пріоритет'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='quantity_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Видано'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='quantity_requested',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Замовлено'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Локація'),
        ),
    ]
