# Generated by Django 6.0 on 2026-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userrequest_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта отримувача'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота отримувача'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Довгота'),
        ),
    ]
