# Generated by Django 6.0 on 2026-05-17 08:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userrequest_latitude_userrequest_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='due_date',
            field=models.DateField(default=app.models.get_default_due_date, verbose_name='Граничний термін виконання'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Кількість для видачі'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість на складі'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='quantity_allocated',
            field=models.PositiveIntegerField(default=0, verbose_name='Виділена кількість'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='quantity_requested',
            field=models.PositiveIntegerField(verbose_name='Запитувана кількість'),
        ),
    ]
