# Generated by Django 6.0 on 2026-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userrequest_due_date_alter_distributionitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='auto_extend',
            field=models.BooleanField(default=True, verbose_name='Автопродовження терміну'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('partial', 'Частково'), ('done', 'Виконана'), ('expired', 'Протермінована')], default='new', max_length=20),
        ),
    ]
