# Generated by Django 6.0 on 2026-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userrequest_auto_extend_alter_userrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='extension_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість автопродовжень'),
        ),
    ]
