# Generated by Django 6.0 on 2026-05-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userrequest_extension_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Термін придатності партії'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Виділена кількість упаковок/штук'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unit', verbose_name='Логістична упаковка'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість упаковок/штук'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Одиниця виміру (пакування)'),
        ),
    ]
